function mybarplot(ymatrix1, fn)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 28-Apr-2016 11:19:12

% Create figure
figure1 = figure(fn);
clf

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'Test Case 1','Test Case 2','Test Case 3'...
    ,'Test Case 4', 'Test Case 5'},...
    'XTick',[1.5 4.5 7.5 10.5 13.5], 'FontSize', 12);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','Optimal Scheme');
set(bar1(2),'DisplayName','Approximate Scheme');
set(bar1(3),'DisplayName','Deterministic Scheme');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','East', 'FontSize', 14);

original_ylim = ylim;
ylim(1.1*original_ylim)
for x = [1 4 7 10 13];
    text(x-0.4, 1.05*original_ylim(1), 'avg', ...
        'FontSize', 12);
    text(x+0.6, 1.05*original_ylim(1), 'prob', ...
        'FontSize', 12);
end
ylabel ('Network operation cost ($/h)', 'FontSize', 15)

