function mybarplot2(ymatrix1, fn)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 28-Apr-2016 11:19:12

% Create figure
figure1 = figure(fn);
clf

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'Scenario 1','Scenario 2','Scenario 3'...
    ,'Scenario 4', 'Scenario 5'},'FontSize', 12,...
    'XTick',[1 2 3 4 5], 'XLim', [0.4, 5.6] );
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','ADA (Algorithm 1)');
set(bar1(2),'DisplayName','PDA (Algorithm 2)');
set(bar1(3),'DisplayName','Approx. avg. dispatch');
set(bar1(4),'DisplayName','Approx. prob. dispatch');
set(bar1(5),'DisplayName','Deterministic dispatch');


% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','East');

% original_ylim = ylim;
% ylim(1.1*original_ylim)
% for x = [1 4 7 10 13];
%     text(x-0.4, 1.05*original_ylim(1), 'avg', ...
%         'FontSize', 12);
%     text(x+0.6, 1.05*original_ylim(1), 'prob', ...
%         'FontSize', 12);
% end
ylabel ('Network operation cost [$/h]', 'FontSize', 15)

